#!/usr/bin/bash

set -euo pipefail

# Uncomment the below lines to help debug script execution.
# set -x
# readonly DEBCONF_DEBUG=developer
# export DEBCONF_DEBUG

# Include debconf shell utility library
. /usr/share/debconf/confmodule

# Clear all cached questions/answers.
db_purge
