#pragma once

#include <cstdint>
#include <exception>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

/**
 * @brief Properties of an attenuator.
 */
struct RfAttenuatorProperties
{
    std::vector<uint32_t> Channels;

    double AttenuationRangeDbmMin;
    double AttenuationRangeDbmMax;
    double AttenuationStepDbmMin;
    double AttenuationStepDbmMax;
    double AttenuationAccuracyDbmMin;
    double AttenuationAccuracyDbmMax;

    uint32_t FrequencyBandwidthMHzMin;
    uint32_t FrequencyBandwidthMHzMax;

    bool SupportsSweep{ false };

    std::optional<std::string> Identification;
};

/**
 * @brief Arguments needed to create an attenuator which uses a TCP-based
 * transport.
 */
struct RfAttenuatorConnectionArgumentsTcp
{
    std::string IpAddress;
    uint16_t Port;
};

/**
 * @brief Base class for all exceptions that can be generated by an attenuator.
 */
struct RfAttenuatorException : public std::exception
{
    virtual ~RfAttenuatorException() = default;
};

/**
 * @brief Interface for controlling a radio frequency attenuator.
 */
struct IRfAttenuatorController
{
    virtual ~IRfAttenuatorController() = default;

    /**
     * @brief Reset the attenuator hardware to its initial/power-up state.
     *
     * This is expected to reset/clear any state associated with the device.
     */
    virtual void
    Reset() = 0;

    /**
     * @brief Get the properties of the attenuator device.
     *
     * @return RfAttenuatorProperties The current effective properties of the
     * attenuator device.
     */
    virtual RfAttenuatorProperties
    GetProperties() = 0;

    /**
     * @brief Get the current attenuation, in dBm.
     *
     * @param channel The channel to get the attenuation value for.
     * @return double The current attenuation value of the channel, in dBm.
     */
    virtual double
    GetAttenuationForChannel(uint32_t channel) = 0;

    /**
     * @brief Set the attenuation for the specified channel.
     *
     * @param channel The channel to set the attenuation for.
     * @param attenuation The attenuation value to set, in dBm.
     * @return true If the attenuation was updated successfully.
     * @return false If the attenuation was not updated successfully.
     */
    virtual bool
    SetAttenuationForChannel(uint32_t channel, double attenuation) = 0;
};
