 
name: 'build-on-host'
description: 'Build the repository on the runner host system'
inputs:
  build-type:
    required: false
    default: 'Debug'
    description: 'The CMake build type (CMAKE_BUILD_TYPE) to run.'
  install:
    required: false
    default: 'false'
    description: 'Invoke CMake install for the project'
  test:
    required: false
    default: 'true'
    description: 'Invoke CMake CTest for the project'
  package:
    required: false
    default: 'false'
    description: 'Invoke CMake CPack for the project'
  publish-artifacts:
    required: false
    default: 'false'
    description: 'Publish build artifacts'
  preset-name:
    required: false
    default: 'dev-windows'
    description: 'The name of the preset to use for all CMake operations (configure, build, test, install, package)'
  vcpkg-binarycache:
    required: false
    default: 'true'
    description: 'Use the vcpkg binary cache'
runs:
  using: 'composite'
  steps:
  - name: Configure vcpkg to use Github Actions Cache 
    if: ${{ inputs.vcpkg-binarycache == 'true' }}
    uses: actions/github-script@v6
    with:
      script: |
        core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

  - name: Install vcpkg dependencies with Github Actions Cache
    if: ${{ inputs.vcpkg-binarycache == 'true' }}
    run: vcpkg install --binarysource="clear;x-gha,readwrite" --clean-buildtrees-after-build --clean-downloads-after-build
    shell: pwsh

  - name: CMake Configure
    if: ${{ ! inputs.arch }}
    run: cmake --preset ${{ inputs.preset-name }} --fresh -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
    shell: pwsh

  - name: CMake Configure Cross-Compile ${{ inputs.arch }}
    if: ${{ inputs.arch }}
    run: cmake --preset ${{ inputs.preset-name }} --fresh -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -DNETREMOTE_DISABLE_TESTS=TRUE -A ${{ inputs.arch }}
    shell: pwsh

  - name: CMake Build
    run: cmake --build --preset ${{ inputs.preset-name }} --config ${{ inputs.build-type }}
    shell: pwsh

  - name: CMake Test (ctest)
    if: ${{ inputs.test == 'true' && ! inputs.arch }}
    run: ctest --preset ${{ inputs.preset-name }} -C ${{ inputs.build-type }}
    shell: pwsh

  - name: CMake Install
    if: inputs.install == 'true'
    run: cmake --build --preset ${{ inputs.preset-name }} --target install --config ${{ inputs.build-type }}
    shell: pwsh

  - name: CMake Package (cpack)
    if: inputs.package == 'true'
    run: cpack --preset ${{ inputs.preset-name }} -C ${{ inputs.build-type }}
    shell: pwsh

  - name: Publish Artifacts
    if: inputs.publish-artifacts == 'true'
    uses: actions/upload-artifact@v3
    with:
      name: release-package-${{ runner.os }}-${{ inputs.build-type }}-${{ inputs.arch != '' && inputs.arch || runner.arch }}
      path: |
        ${{ github.workspace }}/out/package/${{ inputs.preset-name }}/*.tar.*
        ${{ github.workspace }}/out/package/${{ inputs.preset-name }}/*.zip
