
services:
  netremote:
    image: netremote
    build:
      context: ./data
      dockerfile: ../images/netremote/Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    profiles:
      - dontstart

  netremote-dev:
    image: netremote-dev
    build:
      context: ./data
      dockerfile: ../images/netremote/dev/Dockerfile
    tty: true
    stdin_open: true
    privileged: true

  netremote-dev-hostapd:
    image: netremote-dev-hostapd
    build:
      context: ./data
      dockerfile: ../images/netremote/dev/hostapd/Dockerfile
    tty: true
    stdin_open: true
    privileged: true
