
services:
  netremote-dev:
    volumes:
      - ../..:/workspaces:cached
      - workspace:/workspace

  netremote-dev-hostapd:
    volumes:
      - ../..:/workspaces:cached
      - workspace:/workspace

volumes:
  workspace:
