#!/usr/bin/bash

set -euo pipefail

# Uncomment the below two lines to help debug the script.
set -x
DEBCONF_DEBUG=developer

# Include debconf shell utility library
. /usr/share/debconf/confmodule
. $(dirname $0)/netremote-network-config.confnetplan

function main() {
    # Update the network bridge interfaces question with the list of bridge choices. 
    db_subst ${QUESTION_NETWORK_BRIDGES} ${QUESTION_NETWORK_BRIDGE_CHOICES_VAR} ${QUESTION_NETWORK_BRIDGE_CHOICES}

    # Prompt the user for the interfaces for which a virtual network bridge should be created.
    db_clear
    db_fset ${QUESTION_NETWORK_BRIDGES} seen false

    # Prompt to select interfaces to create network bridges for.
    db_input high ${QUESTION_NETWORK_BRIDGES} || true
    db_go || true

    # Ensure the configuration file has been created.
    netplan_configuration_create
}

main "$@"
