#!/usr/bin/bash

set -euo pipefail

# Uncomment the below two lines to help debug the script.
# set -x
# DEBCONF_DEBUG=developer

# Include debconf shell utility library
. /usr/share/debconf/confmodule

db_get netremote/network/bridge-interfaces || true
ETHERNET_INTERFACES_SELECTED_FOR_BRIDGES=${RET//\, / }

echo "Ethernet interfaces selected: ${ETHERNET_INTERFACES_SELECTED_FOR_BRIDGES}"

# TODO: modify netplan configuration and add bridge interface description for each interface.
# - possibly just generate the configuration file instead.
# - invoke `netplan generate`
# - invoke `netplan apply`
