
services:
  netremote-dev:
    build:
      context: netremote-dev
      target: netremote-dev
    tty: true
    stdin_open: true
    privileged: true
    # Enable debugging for ptrace-based debuggers (C++, Go, Rust).
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  netremote-dev-stateless: 
    extends: netremote-dev
    volumes:
      - ../..:/workspaces:cached
