
name: 'Build Windows 📎'

on: 
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        type: choice
        options:
          - 'Debug'
          - 'Release'
          - 'RelWithDebInfo'
          - 'MinSizeRel'
        default: 'Debug'

jobs:
  build:
    name: build windows
    permissions:
      contents: read
      actions: read
      security-events: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-with-host
        with:
          build-type: ${{ inputs.build-type }}
          preset-name: 'dev-windows'
          install: false
          test: false 
          package: false 
          publish-artifacts: false
 