# Primary workflow that runs on each pull request and push to the primary
# branches, develop and main.

name: CI/CD

# Run on workflow dispatch to allow manual triggering of the workflow, and run
# on pushes and PRs to the main branches to enforce code quality and test
# coverage.
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build-validation:
    name: Build Validation
    permissions:
      contents: read
      actions: read
      security-events: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      build-types: "[ 'Debug' ]"
      test: true
      preset-name: 'cicd'
